version: 2

jobs:

  build-python35:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run: sudo apt-get install python make
      - run: make deps-ubuntu deps-test deps install repo/assets
      - run: make test

workflows:
  version: 2
  build:
    jobs:
      - build-python35
